name: Start Server with ngrok
on: [workflow_dispatch]  # Manually trigger

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start ngrok
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http https://v3accntc2.internal:8080 --host-header="v3accntc2.internal" --log=".ngrok.log" &
          sleep 5
          URL=$(grep -o -E "https?://[^ ]+" .ngrok.log)
          echo "Public URL: $URL"
          npm install
          nohup node server.cjs &
          echo "server is go on $URL"    
          
      - name: install cloudflare-warp
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg &&
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list &&
          sudo apt-get update && sudo apt-get install -y cloudflare-warp &&
          sudo sysctl -w net.ipv4.ip_forward=1

      - name: connect to warp
        run: |
          warp-cli connector new eyJhIjoiOTBmNDQ1ZGZiMmEyYTA4NzExMTJhMTU1N2ZmMzliY2IiLCJ0IjoiYWI2MjEyY2MtZDFiZS00MWUwLTg2NDAtZmYyNmQxMWIxNzljIiwicyI6ImZMWnJMa3pIdmFxUmhnOUtXeWRxeFdlRDJUNU1ndE8rVk9yMFJBcVk5bGs9In0= && 
          warp-cli connect
          sleep: 1080
